"""id

Revision ID: 4b2400984e68
Revises: 2e0f6f4c113d
Create Date: 2024-02-07 08:59:29.461699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2400984e68'
down_revision = '2e0f6f4c113d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('speciality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'speciality')
    # ### end Alembic commands ###
